name: Release a new version

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-n-publish-to-pypi:
    name: Build and publish project to PyPI (test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry
      - name: set testpypi as the repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: Configure API token
        run: poetry config pypi-token.testpypi "${{ secrets.TESTPYPI_API_TOKEN }}"
      - name: Build and then publish fotoobo to PyPI
        run: poetry publish --build --repository testpypi

  build:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: WHATSNEW.md
          draft: false
          prerelease: false
