name: testing
run-name: testing workflow invoked by ${{ github.actor }}

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-ansi
      - name: Analyzing the code with pylint
        run: |
          poetry run tox -e pylint
      - name: Type checking with mypy
        run: |
          poetry run tox -e mypy
      - name: Upload mypy report
        uses: actions/upload-artifact@v3
        with:
          name: mypy report
          path: mypy.xml
      - name: Check formatting with black
        run: |
          poetry run tox -e black
      - name: Test create requirements file for readthedocs.io
        run: |
          poetry run tox -e requirements
      - name: Test create docs
        run: |
          poetry run tox -e docs
